export const ACTION_TYPES = {
  GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',

  GET_SELECTED_COUNTRY_REQUEST: 'GET_SELECTED_COUNTRY_REQUEST',
  GET_SELECTED_COUNTRY_SUCCESS: 'GET_SELECTED_COUNTRY_SUCCESS',
  GET_SELECTED_COUNTRY_FAILURE: 'GET_SELECTED_COUNTRY_FAILURE',
  REMOVE_SELECTED_COUNTRY: 'REMOVE_SELECTED_COUNTRY',
}
